/// cutscene const_cutscene_quest_ufo_ufo();

var l=ds_list_create();
ds_list_add(l, args(scr_lock_set));
ds_list_add(l, args(scr_move_to_ext, NPCs.NPCUFOUFO, scr_MoveToMoon));
ds_list_add(l, args(scr_fade, c_black, 1, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_fade, c_black, 0, 1));
ds_list_add(l, args(scr_move_to, NPCs.ActivePlayer, 8320, 11616, 24, Directions.south));
ds_list_add(l, args(scr_lerp_towards, NPCs.NPCUFOUFO, 8320, 11840, 64, 0.05));
ds_list_add(l, args(scr_wait, 4));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 1));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 2));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_effect_create, EffectUFOHalo, 8320, 11840, 64, 0));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_move_to, NPCs.NPCUFOLGM, 8320, 11840, 48, Directions.north));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOLGM, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOLGM, false));
ds_list_add(l, args(scr_walk, NPCs.NPCUFOLGM, MOVE_SPEED_WALK, Directions.north));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_stop, NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_set_multi_option, "Um . . . hello?", 0, "I come in peace?", 0))
ds_list_add(l, args(scr_talk, string_atob_cipher("Greetings, Earthling.")));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, string_atob_cipher("I have something for you.")));
ds_list_add(l, args(scr_add_item, Items.ALIENMEMO2, 1));
ds_list_add(l, args(scr_set_multi_option, ". . . thank you?", 0, "Huh?", 0))
ds_list_add(l, args(scr_talk, string_atob_cipher("Use it well.")));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_turn, NPCs.NPCUFOLGM, 5, Directions.south, true));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_walk, NPCs.NPCUFOLGM, MOVE_SPEED_WALK, Directions.south));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_stop, NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_turn, NPCs.NPCUFOLGM, 5, Directions.north, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_move_to, NPCs.NPCUFOLGM, 8320, 11840, -32, Directions.north));
ds_list_add(l, args(scr_effect_set_target_alpha, 0, 0));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_effect_destroy, 0));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 1));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 0));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_lerp_towards_ext, NPCs.NPCUFOUFO, scr_LerpToMoon, 0.005));
ds_list_add(l, args(scr_wait, 4));
ds_list_add(l, args(scr_fade, c_black, 1, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_unlock_onto_actor));
ds_list_add(l, args(scr_fade, c_black, 0, 1));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_lock_unset));

return l;
