var l=ds_list_create();
ds_list_add(l, args(scr_lock_set));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_01, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_02, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_03, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_04, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_talk, "Greetings!", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_set_multi_option, "Yeah!", 0, "You bet!", 1));
ds_list_add(l, args(scr_talk, "Are you the new hire?", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Glad you made it! We typically take the noobs on a tour of the Aviary first thing just so they can get a feel for the place, but before we can do that I need you to fill out some quick paperwork for me.", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_string_input_set, World.random_nato_name, 32));
ds_list_add(l, args(scr_talk, "First! What is your name?", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_string_input_hide));
ds_list_add(l, args(scr_set_player_name));
ds_list_add(l, args(scr_string_input_set, World.random_nato_name, 32));
ds_list_add(l, args(scr_talk, "Second! What do you want us to call you around here?", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_string_input_hide));
ds_list_add(l, args(scr_set_player_nick));
ds_list_add(l, args(scr_set_multi_option, "Dude", 0, "Girl", 1, "I like frogs", 2));
ds_list_add(l, args(scr_talk, "Third! Would you rather play as a dude or a girl?", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_set_player_gender, Genders.male));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_set_player_gender, Genders.female));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 2, scr_set_player_gender, Genders.owl));
ds_list_add(l, args(scr_talk, "Now before I forget, you should make a habit of keeping this on you at all times. Just in case.", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_add_item, Items.ID, 1));
ds_list_add(l, args(scr_talk, "Okay, that's all! Now to show you around the Aviary. This way!", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_05, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_06, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_quest_begin, Quests.qMainAct1));
ds_list_add(l, args(scr_camera_unlock_onto_actor));
ds_list_add(l, args(scr_lock_unset));

return l;
