enum Locations {
    NONE,
    AVIARY,
    MARSH,
    POND_REED,
    POND_DRAGON,
    RING,
    FOREST,
    TOWN,
    CAMPSITE,
    UNDERGROUND_MAIN,
    UNDERGROUND_TO_FOREST_A,
    UNDERGROUND_TO_FOREST_B,
    UNDERGROUND_TO_FOREST_C,
    UNDERGROUND_TO_AVIARY_UNDERGROUND,
    UNDERGROUND_TO_RAVINE_UNDERGROUND,
    UNDERGROUND_TO_FARM_UNDERGROUND,
    UNUSED15,
    UNUSED16,
    UNUSED17,
    UNUSED18,
    UNUSED19,
    UNUSED20,
    UNUSED21,
    UNUSED22,
    UNUSED23,
    UNUSED24,
    UNUSED25,
    UNUSED26,
    UNUSED27,
    UNUSED28,
    UNUSED29,
    UNUSED30,
    UNUSED31,
    UNUSED32,
    UNUSED33,
    UNUSED34,
    UNUSED35,
    UNUSED36,
    UNUSED37,
    UNUSED38,
    UNUSED39,
    UNUSED40,
    UNUSED41,
    UNUSED42,
    UNUSED43,
    UNUSED44,
    UNUSED45,
    UNUSED46,
    UNUSED47,
    UNUSED48,
    UNUSED49,
    UNUSED50,
    UNUSED51,
    UNUSED52,
    UNUSED53,
    UNUSED54,
    UNUSED55,
    UNUSED56,
    UNUSED57,
    UNUSED58,
    UNUSED59,
    UNUSED60,
    UNUSED61,
    UNUSED62,
    UNUSED63,
    UNUSED64,
    UNUSED65,
    UNUSED66,
    UNUSED67,
    UNUSED68,
    UNUSED69,
    UNUSED70,
    UNUSED71,
    UNUSED72,
    UNUSED73,
    UNUSED74,
    UNUSED75,
    UNUSED76,
    UNUSED77,
    UNUSED78,
    UNUSED79,
    UNUSED80,
    UNUSED81,
    UNUSED82,
    UNUSED83,
    UNUSED84,
    UNUSED85,
    UNUSED86,
    UNUSED87,
    UNUSED88,
    UNUSED89,
    UNUSED90,
    UNUSED91,
    UNUSED92,
    UNUSED93,
    UNUSED94,
    UNUSED95,
    UNUSED96,
    UNUSED97,
    UNUSED98,
    UNUSED99,
    UNUSED100,
    UNUSED101,
    UNUSED102,
    UNUSED103,
    UNUSED104,
    UNUSED105,
    UNUSED106,
    UNUSED107,
    UNUSED108,
    UNUSED109,
    UNUSED110,
    UNUSED111,
    UNUSED112,
    UNUSED113,
    UNUSED114,
    UNUSED115,
    UNUSED116,
    UNUSED117,
    UNUSED118,
    UNUSED119,
    UNUSED120,
    UNUSED121,
    UNUSED122,
    UNUSED123,
    UNUSED124,
    UNUSED125,
    UNUSED126,
    UNUSED127,
    UNUSED128,
    UNUSED129,
    UNUSED130,
    UNUSED131,
    UNUSED132,
    UNUSED133,
    UNUSED134,
    UNUSED135,
    UNUSED136,
    UNUSED137,
    UNUSED138,
    UNUSED139,
    UNUSED140,
    UNUSED141,
    UNUSED142,
    UNUSED143,
    UNUSED144,
    UNUSED145,
    UNUSED146,
    UNUSED147,
    UNUSED148,
    UNUSED149,
    //Test
    Testing,
    DemoShore,
    DemoMountain
}

globalvar all_locations;

all_locations=array_add(Locations.DemoMountain);

all_locations[Locations.NONE]=add_location("None", "A placeholder location.", b_icon_unused, AudioGroups.none, Environments.none);

for (var i=1; i<=Locations.DemoShore; i++){
    all_locations[i]=add_location("Unused"+string(i), "A placeholder location. Unused so far.", b_icon_unused, AudioGroups.mountain, Environments.mountain);
}

all_locations[Locations.DemoMountain]=add_location("Demo Mountain", "Used as a testing grounds.", b_icon_unused, AudioGroups.mountain, Environments.mountain);

all_locations[Locations.AVIARY]=add_location("Aviary", "The main focus of this game.", b_icon_route_1, AudioGroups.aviary, Environments.mountain);
all_locations[Locations.MARSH]=add_location("Marsh", "The surrounding region.", b_icon_route_2, AudioGroups.mountain, Environments.mountain);
all_locations[Locations.POND_REED]=add_location("Reed Pond", "A long-ish pond pond.", b_icon_route_2, AudioGroups.mountain, Environments.mountain);
all_locations[Locations.POND_DRAGON]=add_location("Dragon Pond", "A small-ish pond with some funny islands.", b_icon_route_2, AudioGroups.mountain, Environments.mountain);
all_locations[Locations.RING]=add_location("The Ring", "A mysterious hill with a crater in it.", b_icon_route_2, AudioGroups.mountain, Environments.mountain);
all_locations[Locations.FOREST]=add_location("The Forest", "A forest. Surely lots of different birds live here.", b_icon_route_2, AudioGroups.forest, Environments.mountain);
all_locations[Locations.TOWN]=add_location("Town", "A town floating on the lake. Because ???", b_icon_route_2, AudioGroups.town, Environments.mountain);
all_locations[Locations.CAMPSITE]=add_location("The Campsite", "People come here when they want to spend the night outdoors sometimes.", b_icon_route_2, AudioGroups.forest, Environments.mountain);

all_locations[Locations.UNDERGROUND_MAIN]=add_location("Underground", "The caverns beneath the earth.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_FOREST_A]=add_location("Underground (Zone A)", "You can go up to the forest here.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_FOREST_B]=add_location("Underground (Zone A)", "You can go up to the forest here.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_FOREST_C]=add_location("Underground (Zone A)", "You can go up to the forest here.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_AVIARY_UNDERGROUND]=add_location("Underground (Zone A)", "Transfer to another cavern.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_RAVINE_UNDERGROUND]=add_location("Underground (Zone A)", "Transfer to another cavern.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
all_locations[Locations.UNDERGROUND_TO_FARM_UNDERGROUND]=add_location("Underground (Zone A)", "Transfer to another cavern.", b_icon_route_2, AudioGroups.cave, Environments.underground_generic);
