/// cutscene const_cutscene_quest_ufo_astronomer_b();

var l=ds_list_create();
ds_list_add(l, args(scr_lock_set));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCUFOAstronomerB, NPCs.ActivePlayer));
ds_list_add(l, args(scr_talk, "If you're right and aliens do exist, I'll be the happist man alive."));
ds_list_add(l, args(scr_do_if, scr_GetQuestUFOB, Misc.equal, false, scr_goto, "end"));

ds_list_add(l, args(scr_move_to_ext, NPCs.NPCUFOUFO, scr_MoveToMoon));
ds_list_add(l, args(scr_fade, c_black, 1, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_fade, c_black, 0, 1));
ds_list_add(l, args(scr_move_to, NPCs.ActivePlayer, 8192, 11584, 24, Directions.west));
ds_list_add(l, args(scr_lerp_towards, NPCs.NPCUFOUFO, 8320, 11840, 64, 0.05));
ds_list_add(l, args(scr_wait, 4));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCUFOAstronomerB, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 1));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 2));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_effect_create, EffectUFOHalo, 8320, 11840, 64, 1));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_move_to, NPCs.NPCUFOLGM, 8320, 11840, 48, Directions.north));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOLGM, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOLGM, false));
ds_list_add(l, args(scr_walk, NPCs.NPCUFOLGM, MOVE_SPEED_WALK, Directions.north));
ds_list_add(l, args(scr_wait, 1.5));
ds_list_add(l, args(scr_stop, NPCs.NPCUFOLGM));

ds_list_add(l, args(scr_talk, "Egads! Is this real? Am I dreaming?", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_talk, "This is real, isn't it?", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_talk, string_atob_cipher("It sure is."), NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_talk, string_atob_cipher("So, what do you say? Are you coming with us?"), NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOAstronomerB, true));
ds_list_add(l, args(scr_jump, NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCUFOAstronomerB, false));
ds_list_add(l, args(scr_talk, "I can understand you . . .", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_talk, "You're asking if I want to go with you to explore the stars?", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_talk, "Yes! Yes, of course I'm coming!", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCUFOAstronomerB, NPCs.ActivePlayer));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_push, 0, scr_GetPlayerName));
ds_list_add(l, args(scr_talk, "&0! Thank you so much for this!", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_talk, "You can have this as my thanks. I won't be needing it anymore.", NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_move_to, NPCs.OBJUFOTelescope, 8192, 11840, -100, Directions.west));
ds_list_add(l, args(scr_turn, NPCs.NPCUFOLGM, 5, Directions.south, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_walk, NPCs.NPCUFOLGM, MOVE_SPEED_WALK, Directions.south));
ds_list_add(l, args(scr_wait, 1.5));
ds_list_add(l, args(scr_stop, NPCs.NPCUFOLGM));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_turn, NPCs.NPCUFOLGM, 5, Directions.north, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_move_to, NPCs.NPCUFOLGM, 8320, 11840, -32, Directions.north));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCUFOAstronomerB, NPCs.NPCUFOUFO));
ds_list_add(l, args(scr_walk, NPCs.NPCUFOAstronomerB, MOVE_SPEED_WALK, Directions.south));
ds_list_add(l, args(scr_wait, 1.9));
ds_list_add(l, args(scr_stop, NPCs.NPCUFOAstronomerB));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_turn, NPCs.NPCUFOAstronomerB, 5, Directions.north, true));
ds_list_add(l, args(scr_wait, 1));

ds_list_add(l, args(scr_move_to, NPCs.NPCUFOAstronomerB, 8320, 11840, -32, Directions.north));
ds_list_add(l, args(scr_effect_set_target_alpha, 0, 0));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_effect_destroy, 1));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 1));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_set_model_index, NPCs.NPCUFOUFO, 0));
ds_list_add(l, args(scr_wait, 0.25));
ds_list_add(l, args(scr_lerp_towards_ext, NPCs.NPCUFOUFO, scr_LerpToMoon, 0.005));
ds_list_add(l, args(scr_fade, c_black, 1, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_camera_unlock_onto_actor));
ds_list_add(l, args(scr_fade, c_black, 0, 1));
ds_list_add(l, args(scr_keyword, "end"));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_lock_unset));

return l;
