var l=ds_list_create();
ds_list_add(l, args(scr_lock_set)); 
ds_list_add(l, args(scr_talk, "It's a fountain of water!"));
ds_list_add(l, args(scr_set_multi_option, "Throw some money in!", 0, "Check the bottom.", 1, "Nothing, really.", 2));
ds_list_add(l, args(scr_show_player_money));
ds_list_add(l, args(scr_talk, "What would you like to do with the fountain?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_hide_player_money));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_goto, "fish"));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 2, scr_goto, "decline"));
ds_list_add(l, args(scr_do_if, scr_GetMoney, Misc.equal, 0, scr_goto, "broke"));
ds_list_add(l, args(scr_talk, "Chucked a coin into the fountain!"));
ds_list_add(l, args(scr_GiveMoneyToMe, 1));
ds_list_add(l, args(scr_TakeMoney, 1));
ds_list_add(l, args(scr_goto, "finish"));
ds_list_add(l, args(scr_keyword, "fish"));
ds_list_add(l, args(scr_do_if, scr_GetMyMoney, Misc.equal, 0, scr_goto, "zero"));
ds_list_add(l, args(scr_push, 0, scr_GetMyMoney));
ds_list_add(l, args(scr_GiveMyMoney));
ds_list_add(l, args(scr_SetMyMoney, 0));
ds_list_add(l, args(scr_talk, "You searched the fountain and found $ &0!"));
ds_list_add(l, args(scr_goto, "finish"));
ds_list_add(l, args(scr_keyword, "zero"));
ds_list_add(l, args(scr_talk, "You didn't find anything in the fountain."));
ds_list_add(l, args(scr_goto, "finish"));
ds_list_add(l, args(scr_keyword, "broke"));
ds_list_add(l, args(scr_talk, "It turns out that you don't have any money."));
ds_list_add(l, args(scr_goto, "finish"));
ds_list_add(l, args(scr_keyword, "decline"));
ds_list_add(l, args(scr_talk, "Decided against doing anything with the fountain."));
ds_list_add(l, args(scr_goto, "finish"));
ds_list_add(l, args(scr_keyword, "finish"));
ds_list_add(l, args(scr_lock_unset));

return l;
