var l=ds_list_create();
ds_list_add(l, args(scr_lock_set));
ds_list_add(l, args(scr_push_raw, 0, Quests.qDragon));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.not_equal, 100, scr_goto, "end"));
ds_list_add(l, args(scr_talk, "You found a . . ."));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_place_at_me, NPCs.NPCDragonDragon, NPCs.NPCDragonChest, true, 0, 0, 32));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCDragonDragon, NPCs.ActivePlayer));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCDragonDragon));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCDragonDragon, true));
ds_list_add(l, args(scr_jump, NPCs.NPCDragonDragon));
ds_list_add(l, args(scr_wait, 2));
ds_list_add(l, args(scr_gravity_force, NPCs.NPCDragonDragon, false));
ds_list_add(l, args(scr_talk, "*dragon noises*", NPCs.NPCDragonDragon));
ds_list_add(l, args(scr_talk, "A dragon popped out!"));
ds_list_add(l, args(scr_set_multi_option, "Are you lost?", 0, "Are you hungry?", 1, "Get the hell out of here!", 2));
ds_list_add(l, args(scr_talk, "What do you do?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_talk, "*dragon noises*", NPCs.NPCDragonDragon));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_talk, "It nods slowly . . ."));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_validate_quests));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_talk, "If only you had a book or something on dragon migration habits . . ."));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_validate_quests));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "*dragon noises*", true));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "It doesn't seem intent on eating you . . ."));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 2, scr_talk, ". . ."));
ds_list_add(l, args(scr_camera_unlock_onto_actor));
ds_list_add(l, args(scr_keyword, "end"));
ds_list_add(l, args(scr_lock_unset));

return l;
