var l=ds_list_create();
ds_list_add(l, args(scr_lock_set));
ds_list_add(l, args(scr_turn_to_face, -1, NPCs.ActivePlayer));
ds_list_add(l, args(scr_set_multi_option, "Good morning!", 1));
ds_list_add(l, args(scr_talk, "Another bright and sunshiny day in the office!"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_push_raw, 0, Quests.qMainAct1));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 500, scr_goto, "q01_500"));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 700, scr_goto, "q01_700"));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 800, scr_goto, "q01_800"));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 1000, scr_goto, "q01_1000"));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 1200, scr_goto, "q01_1200"));
ds_list_add(l, args(scr_push_raw, 0, Quests.qMainAct2));
ds_list_add(l, args(scr_do_if, scr_GetQuestStage, Misc.equal, 100, scr_goto, "q02_000"));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q01_500"));
ds_list_add(l, args(scr_set_multi_option, "Absolutely!", 1, "Certainly!", 2));
ds_list_add(l, args(scr_talk, "Are you ready for your first job?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Glad to see the enthusiasm!"));
ds_list_add(l, args(scr_talk, "We got a call that there's an injured blue jay under the bridge to the east."));
ds_list_add(l, args(scr_set_multi_option, "Consider it done!", 1, "I'm on it!", 2));
ds_list_add(l, args(scr_talk, "Would you mind going and bringing it back, please?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q01_700"));
ds_list_add(l, args(scr_set_multi_option, "I got it.", 1));
ds_list_add(l, args(scr_talk, "Do you have the bird?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Great! Give it to me, I'll try and diagnose what happened to it."));
ds_list_add(l, args(scr_remove_item, Items.MQ01BlueJay, 1));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_talk, "In the mean time, you can make sure that everyone has food and water."));
ds_list_add(l, args(scr_talk, "The bins in the Keymaster's office have food, and there's a well that you can fish fresh water out of out back."));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q01_800"));
ds_list_add(l, args(scr_do_if, scr_GetMQ01_800_Bowls, Misc.equal, false, scr_talk, "I thought you were going to feed and water the birds."));
ds_list_add(l, args(scr_do_if, scr_GetMQ01_800_Bowls, Misc.equal, false, scr_goto, "end"));
ds_list_add(l, args(scr_talk, "You got them all? Good show!"));
ds_list_add(l, args(scr_set_multi_option, "That's pretty cool", 0, "Already?", 1));
ds_list_add(l, args(scr_talk, "Well, you'll be happy to know that the blue jay is doing better."));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Anyway, your next job is to retrieve the pigeon stuck on the roof of the diner in FLOATING TOWN.")); // why is a pigeon stuck on the roof
ds_list_add(l, args(scr_talk, "We don't have a reason for this yet but the quest designer is hoping the writers will be able to think of one soon enough."));
ds_list_add(l, args(scr_set_multi_option, "Nope, none.", 0, "But how do I get onto the roof?", 1));
ds_list_add(l, args(scr_talk, "Any questions?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "You don't know about SOME FANCY TECHNIQUE NAME?"));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "If you're good friends with an animal, you can enter its mind and do some fancy voodoo or something idk to control them."));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "You rescued the blue jay, so there's a good chance you're on his good side. He's in Cage 4. Try it out!"));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 0, scr_talk, "Good, good!"));
ds_list_add(l, args(scr_talk, "Now off you go!"));
ds_list_add(l, args(scr_move_to_marker, NPCs.NPCMQBlueJay, NPCs.WaypointMQ01_800_00, true));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q01_1000"));
ds_list_add(l, args(scr_talk, "Is that the pigeon? Good! I'll take it from here.", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_remove_item, Items.MQ01Pigeon, 1));
ds_list_add(l, args(scr_talk, "You've done a lot of running around today, I think you've earned your break. Talk to me again in-", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_talk, "Hey, boss! Boss!"));
ds_list_add(l, args(scr_jump, NPCs.NPCMQBoss));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_11));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_01, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_13));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_13, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_14));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_14, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQBoss, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_talk, "Someone in THE FOREST called just now. They said they found a harpy eagle with a broken wing or something idk.", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQBoss));
ds_list_add(l, args(scr_talk, "A what? They must be mistaken. Harpy eagles aren't from around here.", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_talk, "That's what I said. He seemed fairly insistent that was what it was, though.", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQBoss));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQBoss, NPCs.ActivePlayer));
ds_list_add(l, args(scr_set_multi_option, "Sounds like fun!", 0, "Sounds like adventure!", 0, "Let's go!", 0));
ds_list_add(l, args(scr_talk, "Well, we can figure out what it is when we get a look at it. \p, you mind doing one more task and going into THE FOREST to find this thing?", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "I like the enthusiasm, as always. The entrance to the forest is out west, not far from where the blue jay was earlier.", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_talk, "Good luck!", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQBoss, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_talk, "Thanks for the information, Greeter. Time to get back to work while \p takes care of things.", NPCs.NPCMQBoss));
ds_list_add(l, args(scr_camera_lock_onto_actor, NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_talk, "No problem.", NPCs.NPCMQGreeter));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_13));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_13, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_11));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_01, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_12));
ds_list_add(l, args(scr_walk_to_waypoint, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_12, MOVE_SPEED_WALK));
ds_list_add(l, args(scr_turn_to_face, NPCs.NPCMQGreeter, NPCs.WaypointMQ00_03));   // this last one is so that he finishes facing the desk
ds_list_add(l, args(scr_camera_unlock_onto_actor));
ds_list_add(l, args(scr_validate_quests));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q01_1200"));
ds_list_add(l, args(scr_set_multi_option, "Here's the eagle.", 1));
ds_list_add(l, args(scr_talk, "\p, you're back. How did it go?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Good show! Now if you'll just give it to me . . ."));
ds_list_add(l, args(scr_remove_item, Items.MQ01Eagle, 1));
ds_list_add(l, args(scr_talk, ". . ."));
ds_list_add(l, args(scr_talk, "Well, that's a little concerning."));
ds_list_add(l, args(scr_set_multi_option, "Er . . . it's a big bird?", 0, "Nope, nothing.", 0, "I did not.", 0));
ds_list_add(l, args(scr_talk, "\p, I don't suppose you got a good look at this guy while you were carrying it back?"));
ds_list_add(l, args(scr_set_multi_option, "That doesn't sound good?", 0, "What?", 0, "I didn't hear a gunshot?", 1));
ds_list_add(l, args(scr_talk, "This appears to be a gunshot wound."));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_do_if, scr_GetMultipleChoice, Misc.equal, 1, scr_talk, "Well, that doesn't mean it didn't happen."));
ds_list_add(l, args(scr_talk, "I'm going to go and dress this fellow up."));
ds_list_add(l, args(scr_set_multi_option, "I'd love to.", 0, "Certainly!", 0));
ds_list_add(l, args(scr_talk, "This isn't really in your job description, but would you mind investigating the source of this event?"));
ds_list_add(l, args(scr_hide_multi_option));
ds_list_add(l, args(scr_talk, "Great. I'll be in the Rehab Barn if you need me."));
ds_list_add(l, args(scr_talk, "Here's a key, by the way. You might find it useful."));
ds_list_add(l, args(scr_add_item, Items.KUNDERGROUND, 1));
ds_list_add(l, args(scr_fade, c_black, 1, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_move_to_marker, NPCs.NPCMQBoss, NPCs.WaypointMQ01_000_00, true));
ds_list_add(l, args(scr_move_to_marker, NPCs.NPCMQEagle, NPCs.WaypointMQ01_000_01, true));
ds_list_add(l, args(scr_fade, c_black, 0, 1));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_validate_quests));  // End Main Quest Act I
ds_list_add(l, args(scr_quest_begin, Quests.qMainAct2));
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "q02_000"));
ds_list_add(l, args(scr_talk, "Hey \p, good work. But please talk to me later. Do you know how hard putting a sling on a bird is?"));   // I have never attempted to put a sling on a bird
ds_list_add(l, args(scr_goto, "end"));

ds_list_add(l, args(scr_keyword, "end"));
ds_list_add(l, args(scr_lock_unset));

return l;
