var l=ds_list_create();
ds_list_add(l, args(scr_lock_set)); 
ds_list_add(l, args(scr_turn_to_face, -1, NPCs.ActivePlayer));
ds_list_add(l, args(scr_talk, "Yo."));
ds_list_add(l, args(scr_camera_unlock));
ds_list_add(l, args(scr_face, NPCs.TestMovement, 270, true));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_walk, NPCs.TestMovement, 1.2, 270));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_face, NPCs.TestMovement, 0, true));
ds_list_add(l, args(scr_stop, NPCs.TestMovement));
ds_list_add(l, args(scr_wait, 0.2));
ds_list_add(l, args(scr_walk, NPCs.TestMovement, 1.2, 0));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_face, NPCs.TestMovement, 90, true));
ds_list_add(l, args(scr_stop, NPCs.TestMovement));
ds_list_add(l, args(scr_wait, 0.2));
ds_list_add(l, args(scr_walk, NPCs.TestMovement, 1.2, 90));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_face, NPCs.TestMovement, 180, true));
ds_list_add(l, args(scr_stop, NPCs.TestMovement));
ds_list_add(l, args(scr_wait, 0.2));
ds_list_add(l, args(scr_walk, NPCs.TestMovement, 1.2, 180));
ds_list_add(l, args(scr_wait, 1));
ds_list_add(l, args(scr_stop, NPCs.TestMovement));
ds_list_add(l, args(scr_wait, 0.5));
ds_list_add(l, args(scr_jump, NPCs.TestMovement));
ds_list_add(l, args(scr_camera_lock));
ds_list_add(l, args(scr_lock_unset));

return l;
